name: CI Pipeline

on:
  push:
    branches:
      - feature/setup_project  # Retaining the original branch name as specified

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23  # Specifying Node.js version 23 as per your requirement
          cache: npm

      - name: Install frontend dependencies
        working-directory: frontend
        run: |
          # Remove old lockfiles and modules
          rm -rf node_modules package-lock.json
          # Install dependencies
          npm install
          # Ensure React 18 and corresponding packages are installed
          npm install react@18 react-dom@18
          # Ensure react-router-dom and its type definitions are installed
          npm install react-router-dom
          npm install --save-dev @types/react-router-dom
          # Ensure TypeScript and necessary type definitions are installed
          npm install --save-dev typescript @types/react @types/react-dom
          # Verify tsconfig.json settings
          if [ ! -f tsconfig.json ]; then
            echo '{
              "compilerOptions": {
                "jsx": "react-jsx",
                "moduleResolution": "node",
                "strict": true
              }
            }' > tsconfig.json
          else
            if ! grep -q '"jsx": "react-jsx"' tsconfig.json; then
              echo 'Please ensure your tsconfig.json has "jsx": "react-jsx" under compilerOptions.'
            fi
          fi

      - name: Install backend dependencies
        working-directory: backend
        run: |
          rm -rf node_modules package-lock.json dist
          # Install dependencies
          npm install
          # Ensure necessary NestJS modules and type declarations are installed
          npm install @nestjs/common @nestjs/core @nestjs/typeorm @nestjs/platform-fastify class-validator typeorm @fastify/cors
          npm install --save-dev @types/node

  build_frontend:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23  # Specifying Node.js version 23 as per your requirement
          cache: npm

      - name: Build frontend
        working-directory: frontend
        run: npm run build

  build_backend:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23  # Specifying Node.js version 23 as per your requirement
          cache: npm

      - name: Build backend
        working-directory: backend
        run: npm run build

  run_tests:
    runs-on: ubuntu-latest
    needs: [build_backend, build_frontend]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23  # Specifying Node.js version 23 as per your requirement
          cache: npm

      - name: Run backend tests
        working-directory: backend
        run: npm test

      - name: Run frontend tests
        working-directory: frontend
        run: npm test
