name: CI Pipeline

on:
  push:
    branches:
      - fetaure/setup_project

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23
          cache: 'npm'

      - name: Install backend dependencies
        run: |
          cd backend
          npm install
          npm install @nestjs/common @nestjs/core @nestjs/typeorm typeorm
          npm install --save-dev @types/node
          npm install @nestjs/jwt passport @nestjs/passport passport-jwt
          npm install --save-dev @types/passport-jwt
          npm install @nestjs/platform-fastify @fastify/cors class-validator

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install
          npm install react react-dom react-router-dom
          npm install --save-dev @types/react @types/react-dom @types/react-router-dom vite-tsconfig-paths
          npm install --save-dev @types/react-router-dom

      - name: Install test dependencies
        run: |
          cd tests
          npm install --no-fund
          npm install --save-dev tsx @cucumber/cucumber wait-on
          npm list tsx @cucumber/cucumber || echo "❌ Dependencies missing!"

  build_backend:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23
          cache: 'npm'

      - name: Build backend
        run: |
          cd backend
          npm run build

  build_frontend:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23
          cache: 'npm'

      - name: Build frontend
        run: |
          cd frontend
          npm run build

  run_cucumber_tests:
    runs-on: ubuntu-latest
    needs: [install_dependencies, build_backend, build_frontend]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23
          cache: 'npm'

      - name: Run Cucumber tests
        run: |
          echo "Running Cucumber tests..."
          node -v

          cd tests
          npm install --no-fund
          npm list tsx @cucumber/cucumber || echo "❌ Dependencies missing!"
          ls -l node_modules/ || echo "❌ node_modules missing!"
          ls -l support/ || echo "❌ world.ts missing!"

          cd ../backend
          echo "Starting backend..."
          npm run start > backend.log 2>&1 & echo $! > backend_pid
          sleep 5
          cat backend.log

          cd ../frontend
          echo "Starting frontend..."
          npm run dev > frontend.log 2>&1 & echo $! > frontend_pid
          cd ../tests

          sleep 5
          curl -I http://localhost:3000 || echo "❌ Backend is NOT running!"
          curl -I http://localhost:5173 || echo "❌ Frontend is NOT running!"

          timeout 60 npx wait-on http://localhost:3000 http://localhost:5173

          npx playwright install --with-deps
          npx cucumber-js --import tsx

          echo "Stopping backend..."
          kill $(cat ../backend/backend_pid) || echo "❌ Failed to stop backend!"
          echo "Stopping frontend..."
          kill $(cat ../frontend/frontend_pid) || echo "❌ Failed to stop frontend!"
