name: CI Pipeline

on:
  push:
    branches:
      - fetaure/setup_project  # Using your branch name

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: npm

      - name: Install backend dependencies
        working-directory: backend
        run: |
          echo "Installing backend dependencies..."
          rm -rf node_modules package-lock.json
          npm cache clean --force
          npm install
          npm install @nestjs/common
          npm install @nestjs/core
          npm install @nestjs/mapped-types

      - name: Install frontend dependencies
        working-directory: frontend
        run: |
          echo "Installing frontend dependencies..."
          rm -rf node_modules package-lock.json
          npm cache clean --force
          npm install
          npm install @nestjs/common
          npm install @nestjs/core
          npm install --save-dev vite-tsconfig-paths

      - name: Install test dependencies
        working-directory: tests
        run: |
          echo "Installing test dependencies..."
          npm install --no-fund
          npm install --save-dev tsx @cucumber/cucumber wait-on
          npx wait-on --version || echo "❌ wait-on not installed!"

  build_backend:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build backend
        working-directory: backend
        run: |
          echo "Building backend..."
          npm install @nestjs/common
          npm install @nestjs/core
          npm install
          npm run build
          mkdir -p dist
          ls -lah dist || echo "❌ Build failed! dist/ folder is missing."

  build_frontend:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build frontend
        working-directory: frontend
        run: |
          echo "Building frontend..."
          npm install @nestjs/common
          npm install @nestjs/core
          npm install
          npm run build
          ls -lah build || echo "❌ Build failed! build/ folder is missing."

  deploy_and_run_tests:
    runs-on: ubuntu-latest
    needs: [build_backend, build_frontend]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ✅ Start Backend
      - name: Start Backend
        working-directory: backend
        run: |
          echo "Starting backend..."
          npm run start > backend.log 2>&1 & echo $! > backend_pid
          sleep 5
          echo "Backend logs:"
          cat backend.log || echo "No logs available."

      # ✅ Start Frontend
      - name: Start Frontend
        working-directory: frontend
        run: |
          echo "Starting frontend..."
          npm run dev > frontend.log 2>&1 & echo $! > frontend_pid
          sleep 5
          echo "Frontend logs:"
          cat frontend.log || echo "No logs available."

      # ✅ Wait for Services to Be Ready
      - name: Wait for services
        run: |
          echo "Waiting for backend and frontend to be ready..."
          timeout 60 npx wait-on http://localhost:3000 http://localhost:5173 || { echo "❌ Backend or frontend did not start in time!"; exit 1; }

      # ✅ Install Playwright Browsers
      - name: Install Playwright
        run: npx playwright install --with-deps

      # ✅ Run Tests
      - name: Run Cucumber Tests
        working-directory: tests
        run: |
          echo "Running Cucumber tests..."
          npx cucumber-js --import tsx

      # ✅ Stop Backend & Frontend
      - name: Stop Backend & Frontend
        run: |
          echo "Stopping backend..."
          kill $(cat backend/backend_pid) || echo "Backend was not running."

          echo "Stopping frontend..."
          kill $(cat frontend/frontend_pid) || echo "Frontend was not running."
