name: CI Pipeline

on:
  push:
    branches:
      - feature/setup_project  # Fixed the branch name typo

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20  # Node.js 23 is not stable, using latest LTS
          cache: npm

      - name: Install backend dependencies
        working-directory: backend
        run: |
          echo "Installing backend dependencies..."
          rm -rf node_modules package-lock.json
          npm cache clean --force
          npm install
          npm install @nestjs/config @nestjs/common @nestjs/core @nestjs/mapped-types

      - name: Install frontend dependencies
        working-directory: frontend
        run: |
          echo "Installing frontend dependencies..."
          rm -rf node_modules package-lock.json
          npm cache clean --force
          npm install
          npm install --save-dev vite-tsconfig-paths

      - name: Install test dependencies
        working-directory: tests
        run: |
          echo "Installing test dependencies..."
          npm install --no-fund
          npm install --save-dev tsx @cucumber/cucumber wait-on
          npm list tsx @cucumber/cucumber || echo "❌ Dependencies missing!"

  build_backend:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build backend
        working-directory: backend
        run: |
          echo "Building backend..."
          npm install
          npm run build

      - name: Cache backend build
        uses: actions/cache@v4
        with:
          path: backend/dist/
          key: ${{ runner.os }}-backend-dist-${{ hashFiles('backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-backend-dist-

  build_frontend:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build frontend
        working-directory: frontend
        run: |
          echo "Building frontend..."
          npm install
          npm run build

      - name: Cache frontend build
        uses: actions/cache@v4
        with:
          path: frontend/build/
          key: ${{ runner.os }}-frontend-build-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-frontend-build-

  run_cucumber_tests:
    runs-on: ubuntu-latest
    needs: [build_backend, build_frontend]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install test dependencies
        working-directory: tests
        run: |
          echo "Installing test dependencies..."
          npm install --no-fund
          npm list tsx @cucumber/cucumber || echo "❌ Dependencies missing!"

      - name: Start backend
        working-directory: backend
        run: |
          echo "Starting backend..."
          nohup npm run start:prod > backend.log 2>&1 & echo $! > backend_pid
          sleep 5
          echo "Backend logs:"
          tail -n 20 backend.log

      - name: Start frontend
        working-directory: frontend
        run: |
          echo "Starting frontend..."
          nohup npm run preview > frontend.log 2>&1 & echo $! > frontend_pid
          sleep 5
          echo "Frontend logs:"
          tail -n 20 frontend.log

      - name: Wait for services
        run: |
          echo "Waiting for backend and frontend to be ready..."
          timeout 60 npx wait-on http://localhost:3000 http://localhost:5173 || { echo "❌ Services not ready!"; exit 1; }

      - name: Install Playwright browsers
        run: |
          echo "Installing Playwright browsers..."
          npx playwright install --with-deps

      - name: Run Cucumber tests
        working-directory: tests
        run: |
          echo "Running Cucumber tests..."
          npx cucumber-js --import tsx || { echo "❌ Cucumber tests failed!"; exit 1; }

      - name: Stop backend
        if: always()
        run: |
          echo "Stopping backend..."
          kill $(cat backend/backend_pid) || echo "❌ Failed to stop backend!"

      - name: Stop frontend
        if: always()
        run: |
          echo "Stopping frontend..."
          kill $(cat frontend/frontend_pid) || echo "❌ Failed to stop frontend!"

      - name: Print logs for debugging
        if: always()
        run: |
          echo "📄 Backend logs:"
          tail -n 50 backend/backend.log || echo "❌ No backend logs found!"
          
          echo "📄 Frontend logs:"
          tail -n 50 frontend/frontend.log || echo "❌ No frontend logs found!"
