name: CI Pipeline

on:
  push:
    branches:
      - fetaure/setup_project  # Retaining the original branch name

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: npm

      - name: Install backend dependencies
        working-directory: backend
        run: |
          echo "Installing backend dependencies..."
          rm -rf node_modules package-lock.json
          npm cache clean --force
          npm install
          npm i --save @nestjs/config
          npm install @nestjs/common
          npm install @nestjs/core
          npm install @nestjs/mapped-types
          npm install

      - name: Install frontend dependencies
        working-directory: frontend
        run: |
          echo "Installing frontend dependencies..."
          rm -rf node_modules package-lock.json
          npm cache clean --force
          npm install
          npm install --save-dev vite-tsconfig-paths

      - name: Install test dependencies
        working-directory: tests
        run: |
          echo "Installing test dependencies..."
          npm install --no-fund
          npm install --save-dev tsx @cucumber/cucumber wait-on
          npx wait-on --version || echo "❌ wait-on not installed!"

  build_backend:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build backend
        working-directory: backend
        run: |
          echo "Building backend..."
          npm install @nestjs/common
          npm install @nestjs/core
          npm run build
          mkdir -p dist
          ls -lah dist || echo "❌ Build failed! dist/ folder is missing!"

      - name: Upload Backend Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-build
          path: backend/dist/

  build_frontend:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build frontend
        working-directory: frontend
        run: |
          echo "Building frontend..."
          npm install @nestjs/common
          npm install @nestjs/core
          npm run build

      - name: Cache Frontend Build
        uses: actions/cache@v4
        with:
          path: frontend/build/
          key: ${{ runner.os }}-frontend-build-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-frontend-build-

  deploy:
    runs-on: ubuntu-latest
    needs: [build_backend, build_frontend]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Backend Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-build
          path: backend/dist/

      - name: Verify Backend Build Exists
        working-directory: backend
        run: |
          echo "Checking if backend build exists before deployment..."
          if [ ! -f dist/main.js ]; then
            echo "❌ ERROR: Backend build is missing! Aborting deployment."
            ls -lah dist
            exit 1
          fi
          echo "✅ Backend build found. Proceeding with deployment."

      - name: Deploy Backend
        working-directory: backend
        run: |
          echo "Deploying backend..."
          scp -r dist/ ubuntu@github.com:imelnic555/react_nodejs_plawyright/backend
          ssh ubuntu@github.com "pm2 restart backend || pm2 start dist/main.js --name backend"

      - name: Deploy Frontend
        working-directory: frontend
        run: |
          echo "Deploying frontend..."
          scp -r build/ ubuntu@github.com:imelnic555/react_nodejs_plawyright/frontend
          ssh ubuntu@github.com "pm2 restart frontend || pm2 start serve --name frontend -- -s build -l 5173"

      - name: Wait for services to start
        run: |
          echo "Waiting for backend and frontend to be ready..."
          timeout 120 npx wait-on http://github.com:imelnic555/react_nodejs_plawyright/backend http://github.com:imelnic555/react_nodejs_plawyright/frontend || { echo "❌ Backend or frontend did not start in time!"; exit 1; }

  run_cucumber_tests:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show Node.js version
        run: node -v

      - name: Verify test dependencies
        working-directory: tests
        run: |
          echo "Checking test dependencies..."
          npm install --no-fund
          npm list tsx @cucumber/cucumber || echo "❌ Dependencies missing!"
          ls -l node_modules/ || echo "❌ node_modules missing!"
          ls -l support/ || echo "❌ world.ts missing!"

      - name: Check Backend Status
        run: |
          echo "Checking if backend is running..."
          curl -I http://github.com:imelnic555/react_nodejs_plawyright/backend || echo "❌ Backend is NOT running!"

      - name: Check Frontend Status
        run: |
          echo "Checking if frontend is running..."
          curl -I http://github.com:imelnic555/react_nodejs_plawyright/frontend || echo "❌ Frontend is NOT running!"

      - name: Install Playwright browsers
        run: |
          echo "Installing Playwright browsers..."
          npx playwright install --with-deps

      - name: Run Cucumber tests
        working-directory: tests
        run: |
          echo "Running Cucumber tests..."
          npx cucumber-js --import tsx

  shutdown_services:
    runs-on: ubuntu-latest
    needs: [run_cucumber_tests]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Shut down backend & frontend after tests
        run: |
          echo "Shutting down backend and frontend after tests..."
          ssh ubuntu@github.com "pm2 stop backend || echo 'Backend not running!'"
          ssh ubuntu@github.com "pm2 stop frontend || echo 'Frontend not running!'"
