name: CI Pipeline

on:
  push:
    branches:
      - fetaure/setup_project

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23
          cache: 'npm'

      - name: Configure Git to use HTTPS instead of SSH
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"

      - name: Force GitHub URLs to Use HTTPS
        run: |
          git config --global --replace-all url."https://github.com/".insteadOf "git@github.com:"
          git config --global --list

      - name: Remove Any Existing SSH Credentials
        run: |
          rm -rf ~/.ssh

      - name: Ensure NPM Uses HTTPS for GitHub Dependencies
        run: |
          npm config set strict-ssl false
          npm config set registry https://registry.npmjs.org/
          npm config list

      - name: Install backend dependencies
        run: |
          cd backend
          rm -rf node_modules package-lock.json dist
          npm install --legacy-peer-deps
          npm install @nestjs/common@latest @nestjs/core@latest @nestjs/typeorm@latest typeorm@latest
          npm install @nestjs/platform-express @nestjs/platform-fastify
          npm install --save-dev @types/node
          npm install @nestjs/jwt passport @nestjs/passport passport-jwt
          npm install --save-dev @types/passport-jwt
          npm install @nestjs/config @nestjs/swagger class-validator class-transformer
          npm rebuild
          npm list @nestjs/common @nestjs/core @nestjs/typeorm || echo "❌ Some dependencies are missing!"

      - name: Install frontend dependencies
        run: |
          cd frontend
          rm -rf node_modules package-lock.json
          npm install --legacy-peer-deps
          npm install react@latest react-dom@latest react-router-dom@latest
          npm install --save-dev @types/react @types/react-dom @types/react-router-dom vite-tsconfig-paths
          npm install --save-dev @types/node
          npm install --save-exact typescript@4.9.5
          npm install --save-dev @typescript-eslint/eslint-plugin@8.26.1 @typescript-eslint/parser@8.26.1
          npm install --save-dev @vitejs/plugin-react
          npm install --save react/jsx-runtime
          npm dedupe

      - name: Ensure correct tsconfig.json settings
        run: |
          cd frontend
          echo '{
            "compilerOptions": {
              "jsx": "react-jsx",
              "moduleResolution": "node",
              "strict": true
            }
          }' > tsconfig.json

      - name: Install test dependencies
        run: |
          cd tests
          rm -rf node_modules package-lock.json
          npm install --legacy-peer-deps
          npm install --save-dev tsx @cucumber/cucumber wait-on
          npm list tsx @cucumber/cucumber || echo "❌ Dependencies missing!"

  build_backend:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23
          cache: 'npm'

      - name: Build backend
        run: |
          cd backend
          npm run build

  build_frontend:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23
          cache: 'npm'

      - name: Build frontend
        run: |
          cd frontend
          npm run build

  run_cucumber_tests:
    runs-on: ubuntu-latest
    needs: [install_dependencies, build_backend, build_frontend]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23
          cache: 'npm'

      - name: Run Cucumber tests
        run: |
          echo "Running Cucumber tests..."
          node -v

          cd tests
          npm install --legacy-peer-deps
          npm list tsx @cucumber/cucumber || echo "❌ Dependencies missing!"
          ls -l node_modules/ || echo "❌ node_modules missing!"
          ls -l support/ || echo "❌ world.ts missing!"

          cd ../backend
          echo "Starting backend..."
          npm run start > backend.log 2>&1 & echo $! > backend_pid
          sleep 5
          cat backend.log

          cd ../frontend
          echo "Starting frontend..."
          npm run dev > frontend.log 2>&1 & echo $! > frontend_pid
          cd ../tests

          sleep 5
          curl -I http://localhost:3000 || echo "❌ Backend is NOT running!"
          curl -I http://localhost:5173 || echo "❌ Frontend is NOT running!"

          timeout 60 npx wait-on http://localhost:3000 http://localhost:5173

          npx playwright install --with-deps
          npx cucumber-js --import tsx

          echo "Stopping backend..."
          kill $(cat ../backend/backend_pid) || echo "❌ Failed to stop backend!"
          echo "Stopping frontend..."
          kill $(cat ../frontend/frontend_pid) || echo "❌ Failed to stop frontend!"
