
name: CI Pipeline

on:
  push:
    branches:
      - fetaure/setup_project  # Retaining the original branch name 

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23  # Use latest Node.js for native TypeScript support1
          cache: npm

      - name: Install backend dependencies
        working-directory: backend
        run: |
          echo "Installing backend dependencies..."
          rm -rf node_modules
          rm -f package-lock.json
          npm cache clean --force
          npm install
          npm i --save @nestjs/config
          npm install @nestjs/common
          npm install @nestjs/core
          npm install @nestjs/mapped-types
          npm install
          npm i --save @nestjs/config
          
      - name: Install frontend dependencies
        working-directory: frontend
        run: |
          echo "Installing frontend dependencies..."
          rm -rf node_modules
          rm -f package-lock.json
          npm cache clean --force
          npm install
          npm install --save-dev vite-tsconfig-paths

      - name: Install test dependencies
        working-directory: tests
        run: |
          echo "Installing test dependencies..."
          npm install --no-fund
          npm install --save-dev tsx @cucumber/cucumber wait-on
          npm list tsx @cucumber/cucumber || echo "❌ Dependencies missing!"

  build_backend:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build backend
        working-directory: backend
        run: |
          echo "Building backend..."
          npm install @nestjs/common
          npm install @nestjs/core
          npm run build

      - name: Cache backend build
        uses: actions/cache@v4
        with:
          path: backend/dist/
          key: ${{ runner.os }}-backend-dist-${{ hashFiles('backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-backend-dist-

  build_frontend:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build frontend
        working-directory: frontend
        run: |
          echo "Building frontend..."
          npm install @nestjs/common
          npm install @nestjs/core
          npm run build

      - name: Cache frontend build
        uses: actions/cache@v4
        with:
          path: frontend/build/
          key: ${{ runner.os }}-frontend-build-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-frontend-build-

  run_cucumber_tests:
    runs-on: ubuntu-latest
    needs: [build_backend, build_frontend]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23
          cache: npm

      - name: Install test dependencies
        working-directory: tests
        run: |
          echo "Installing test dependencies..."
          npm install --no-fund
          npm list tsx @cucumber/cucumber || echo "❌ Dependencies missing!"
          ls -l node_modules/ || echo "❌ node_modules missing!"
          ls -l support/ || echo "❌ world.ts missing!"

      - name: Start backend
        working-directory: backend
        run: |
          echo "Starting backend..."
          npm run start > backend.log 2>&1 & echo $! > backend_pid
          sleep 5
          echo "Backend logs:"
          cat backend.log

      - name: Start frontend
        working-directory: frontend
        run: |
          echo "Starting frontend..."
          npm run dev & echo $! > frontend_pid

      - name: Wait for services
        run: |
          echo "Waiting for backend and frontend to be ready..."
          timeout 60 npx wait-on http://localhost:3000 http://localhost:5173

      - name: Install Playwright browsers
        run: |
          echo "Installing Playwright browsers..."
          npx playwright install --with-deps

      - name: Run Cucumber tests
        working-directory: tests
        run: |
          echo "Running Cucumber tests..."
          npx cucumber-js --import tsx

      - name: Stop backend
        run: |
          echo "Stopping backend..."
          kill $(cat backend/backend_pid) || echo "❌ Failed to stop backend!"

      - name: Stop frontend
        run: |
          echo "Stopping frontend..."
          kill $(cat frontend/frontend_pid) || echo "❌ Failed to stop frontend!"
