name: CI Pipeline

on:
  push:
    branches:
      - feature/setup_project

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out your repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Node.js (v20)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # 3. Install Frontend Dependencies
      - name: Install frontend dependencies
        run: |
          cd frontend
          rm -rf node_modules package-lock.json
          npm ci

      # 4. Ensure correct tsconfig.json (optional if you want to override)
      - name: Ensure correct tsconfig.json settings
        run: |
          cd frontend
          echo '{
            "compilerOptions": {
              "jsx": "react-jsx",
              "moduleResolution": "node",
              "strict": true
            }
          }' > tsconfig.json

      # 5. Install Backend Dependencies
      - name: Install backend dependencies
        run: |
          cd backend
          rm -rf node_modules package-lock.json dist
          npm ci
          npm run build || echo "(If needed, build command here)"

      # 6. Install Test Dependencies
      - name: Install test dependencies
        run: |
          cd tests
          rm -rf node_modules package-lock.json
          npm ci
          npm install --save-dev tsx @cucumber/cucumber wait-on

  build_frontend:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Build frontend
        run: |
          cd frontend
          npm run build

  build_backend:
    runs-on: ubuntu-latest
    needs: build_frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Build backend
        run: |
          cd backend
          npm run build

  run_cucumber_tests:
    runs-on: ubuntu-latest
    needs: [build_backend, build_frontend]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Run Cucumber tests
        run: |
          echo "Running Cucumber tests..."
          node -v

          # Start backend
          cd backend
          echo "Starting backend..."
          npm run start > ../backend.log 2>&1 & echo $! > ../backend_pid
          sleep 5
          cat ../backend.log

          # Start frontend
          cd ../frontend
          echo "Starting frontend..."
          npm run dev > ../frontend.log 2>&1 & echo $! > ../frontend_pid

          # Move to tests folder
          cd ../tests
          sleep 5

          # Quick checks for backend + frontend
          curl -I http://localhost:3000 || echo "❌ Backend is NOT running!"
          curl -I http://localhost:5173 || echo "❌ Frontend is NOT running!"

          # Wait on ports
          timeout 60 npx wait-on http://localhost:3000 http://localhost:5173

          # Set up and run tests
          npx playwright install --with-deps
          npx cucumber-js --import tsx

          # Stop backend + frontend
          echo "Stopping backend..."
          kill $(cat ../backend_pid) || echo "❌ Failed to stop backend!"
          echo "Stopping frontend..."
          kill $(cat ../frontend_pid) || echo "❌ Failed to stop frontend!"
